project:
  type: website
  output-dir: docs

website:
  title: "Calibración de sensores de bajo costo (PM₂.₅)"
  site-url: https://lenpedroso.github.io/Calibracion-de-sensores/
  repo-url: https://github.com/lenpedroso/Calibracion-de-sensores
  navbar:
    left:
      - text: Inicio
        href: index.html     # ← cambia index.qmd por index.html
  search: false              # no necesitas búsqueda si usas HTML fijo

format:
  html:
    theme: cosmo
    toc: false

