project:
  type: website
  output-dir: docs

website:
  title: "Calibración de sensores de bajo costo (PM₂.₅)"
  
  base-url: /Calibracion de sensores/   # Reemplaza con el nombre exacto de tu repo en GitHub
  navbar:
    left:
      - text: Inicio
        href: index.qmd
  search: true

format:
  html:
    theme: cosmo
    toc: true
    toc-location: right
    title-block-banner: "#93c5fd"
    title-block-color: "white"

execute:
  echo: false
  warning: false
  message: false

lang: es


